# Generated by Django 4.2 on 2023-05-03 05:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_avatar_alter_user_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name_plural": "회원"},
        ),
    ]
