# Generated by Django 4.2 on 2023-05-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "카테고리"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name_plural": "댓글"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name_plural": "포스트"},
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
