# Generated by Django 4.2 on 2023-05-09 06:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_comment_author_alter_post_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
