# Generated by Django 4.2 on 2023-05-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medias", "0002_alter_photo_blog_alter_video_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.URLField(),
        ),
    ]
