# Generated by Django 4.2 on 2023-05-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoinKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("coin_name", models.CharField(max_length=30)),
                ("ticker_symbol", models.CharField(max_length=10)),
                ("description", models.TextField()),
                ("website", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
